native-image --no-server \
    -jar target/geogig/libexec/geogig-cli-app-2.0-SNAPSHOT.jar \
    -H:Name=geogig \
    -H:ReflectionConfigurationFiles=native-image/reflect-config.json \
    -H:DynamicProxyConfigurationFiles=native-image/proxy-config.json \
    -H:JNIConfigurationFiles=native-image/jni-config.json \
    -H:ResourceConfigurationFiles=native-image/resource-config.json \
    --allow-incomplete-classpath \
    --initialize-at-build-time=org.postgresql.Driver,org.postgresql.util.SharedTimer,org.hsqldb.jdbc.JDBCDriver,org.sqlite.JDBC \
    --static \
    --no-fallback \
    --report-unsupported-elements-at-runtime \
    -Dorg.geotools.referencing.forceXY=true
